export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"679fa0609e74900024008f9e",
				"679fa0609e74900024008fa1"
			]
		},
		"679fa0609e74900024008f9e": {
			"id": "679fa0609e74900024008f9e",
			"name": "404",
			"pageUrl": "404"
		},
		"679fa0609e74900024008fa1": {
			"id": "679fa0609e74900024008fa1",
			"name": "index",
			"pageUrl": "index"
		}
	},
	"mode": "production",
	"projectType": "create-react-app",
	"site": {
		"styles": {
			"display": "grid"
		},
		"seo": {
			"favicon_32px": "https://uploads.quarkly.io/679fa0609e74900024008f99/images/Untitled%20design.png?v=2025-02-02T19:11:43.985Z",
			"favicon_apple_152px": "https://uploads.quarkly.io/679fa0609e74900024008f99/images/apple-touch%20icon%20Ashimary.png?v=2025-02-02T19:12:34.294Z",
			"favicon_win10_270px": "https://uploads.quarkly.io/679fa0609e74900024008f99/images/Win%2010%20icon%20Ashimary.png?v=2025-02-02T19:18:51.989Z",
			"title": "Ashimary Wigs | Shop Stylish & Natural Looking Wigs",
			"description": "Shop Ashimary Wigs for high-quality, natural-looking women's wigs. Find the perfect style, color, and length. Free shipping available!",
			"og:title": "<meta property=\"og:title\" content=\"Ashimary Wigs: Premium Quality Women's Wigs\" />",
			"og:description": "<meta property=\"og:description\" content=\"Shop Ashimary Wigs for the best selection of human hair wigs.  Find your perfect style today!\" />",
			"og:image": "https://uploads.quarkly.io/679fa0609e74900024008f99/images/Create%20an%20Image%20on%20Ashimary%20Hair__%20Ashimary%20Hair,%20Category%20Womens%20wig,%20Image%20used%20for%20Android%20App%20as%20a%20Fevicon.jpg?v=2025-02-02T20:12:07.475Z",
			"robotsFileType": "autogenerated",
			"customSitemapDomain": "https://www.tkqlhce.com/click-101300629-15820774?sid=7016661"
		}
	}
}